# Generated by Django 3.2.2 on 2021-05-11 13:00

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Schema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('status', models.CharField(choices=[('Ready', 'Ready to download'), ('Processing', 'In progress'), ('Failed', 'Error')], max_length=255, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at ')),
                ('file', models.FileField(blank=True, null=True, upload_to='schemas/', verbose_name='Schema')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schemas', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
        ),
        migrations.CreateModel(
            name='Column',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('type', models.CharField(choices=[('integer', 'Number range'), ('date', 'Date time'), ('email', 'E-mail'), ('phone', 'Phone number'), ('job', 'Job position')], max_length=30, verbose_name='Column type')),
                ('order', models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Column order')),
                ('quantity_range_lower', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Нижняя граница диапазона чисел')),
                ('quantity_range_upper', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Верхняя граница диапазона чисел')),
                ('schema', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='column_in_schemas', to='schemas.schema', verbose_name='Schema')),
            ],
            options={
                'verbose_name': 'Column in schema',
                'verbose_name_plural': 'Columns in schema',
            },
        ),
    ]
