# Generated by Django 3.2.2 on 2021-05-11 13:31

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('schemas', '0002_auto_20210511_1328'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Column',
            new_name='ColumnModel',
        ),
        migrations.RenameModel(
            old_name='Schema',
            new_name='SchemaModel',
        ),
    ]
