# Generated by Django 3.2.2 on 2021-05-13 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schemas', '0004_alter_schemamodel_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='columnmodel',
            name='quantity_range_lower',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='From'),
        ),
        migrations.AlterField(
            model_name='columnmodel',
            name='quantity_range_upper',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='To'),
        ),
    ]
