# Generated by Django 3.2.2 on 2021-05-13 13:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schemas', '0005_auto_20210513_0936'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schemamodel',
            name='file',
        ),
        migrations.CreateModel(
            name='SchemaFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, null=True, upload_to='schemas/', verbose_name='Schema')),
                ('schema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='schemas.schemamodel')),
            ],
        ),
    ]
