# Generated by Django 3.2.2 on 2021-05-13 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schemas', '0006_auto_20210513_1333'),
    ]

    operations = [
        migrations.AddField(
            model_name='schemafile',
            name='status',
            field=models.CharField(blank=True, choices=[('Ready', 'Ready to download'), ('Processing', 'In progress'), ('Failed', 'Error')], max_length=255, null=True, verbose_name='File status'),
        ),
    ]
