# Generated by Django 3.2.2 on 2021-05-15 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schemas', '0007_schemafile_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='schemafile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created at '),
        ),
    ]
