# Generated by Django 3.2.2 on 2021-05-18 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schemas', '0008_schemafile_created_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='schemamodel',
            options={'ordering': ['-created_at'], 'verbose_name': 'Schema', 'verbose_name_plural': 'Schemas'},
        ),
    ]
